version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  pre_build:
    commands:
      - echo Prebuild
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Postbuild
artifacts:
  files:
    - build/*
